### ISSUE TITLE
请教一下这个里面 new BTCTransaction(?)里面的这个是什么

### ISSUE THREAD

**Issue by jackTang11** [QuincySx/BlockchainWallet-Crypto#10]
Transaction transaction= new BTCTransaction(十六进制 TX Byte[]);// HexUtils.fromHex(str) 可以转换 
byte[] signByte = transaction.sign(master);
String signTx = HexUtils.toHex(signByte);

请教一下这个里面 new BTCTransaction(?)里面的这个是什么,我现在要做btc的转账签名,手续费,地址都怎么传,这个十六进制又是怎么生成的

**Comment by QuincySx** [comment]
因为比特币我没有写生成 Transaction 的方法，以太坊写了传入各种参数生成 Transaction，所以 比特币只能去服务器（获其他方式）生成 Transaction ，交由本地签名，
因为好多参数或结果都是16进制 byte 的格式 HexUtils 是用来 String <=> byte[] 相互转换的
