### ISSUE TITLE
BTC创建地址连续2次相同?

### ISSUE THREAD

**Issue by zdyszm** [QuincySx/BlockchainWallet-Crypto#11]
HI：
  请教个问题：我用如下代码，发现不退出程序，连续2次生成的BTC地址是相同的。第三次就不相同了。请问是什么原因？
 try {
                    Log.d(LOGTAG,"==============btc=========================");
                    MnemonicCode mnemonicCode = new MnemonicCode();
                    //参数是助记词的个数

                    //通过助记词产生
                    byte[] random = RandomSeed.random(Words.TWELVE);
                    //(可以通过此代码使用助记词恢复随机数 byte[] bytes = mnemonicCode.toEntropy(mnemonicWordsInAList );)
                    Log.d(LOGTAG,"random = " +  DigitalTrans.byte2hex(random));

                    //生成
                    List<String> mnemonicWordsInAList = mnemonicCode.toMnemonic(random);

                    String s1 = mnemonicWordsInAList.toString();

                    Log.d(LOGTAG,"list = " + mnemonicWordsInAList.toString());

                    //随机创建助记词
                    byte[] seed = MnemonicCode.toSeed(mnemonicWordsInAList, "");

                    Log.d(LOGTAG,"seed = " +  DigitalTrans.byte2hex(seed));
                    ExtendedKey extendedKey = ExtendedKey.create(seed);

                    AddressIndex address = BIP44.m().purpose44()
                            .coinType(CoinTypes.Bitcoin)
                            .account(0)
                            .external()
                            .address(0);

                    Log.e(LOGTAG, "==" + address.toString());
                    CoinPairDerive coinKeyPair = new CoinPairDerive(extendedKey);

                    ECKeyPair master = coinKeyPair.derive(address);

                    try {
                        BTCTransaction btcTransaction = new BTCTransaction(HexUtils.fromHex("02000000018aad5febb0f5165097727eb402d15e96c615560b6d4e0fcbee0882ff589af3220000000000ffffffff0240420f00000000001976a91438ae48c4ff53e9ba952d3c63f200f2dfe04f330188aca0cd8700000000001976a91481f9f80df4efb08e373fa8f2b8896f33e3a270f388ac00000000"));
                        byte[] sign = btcTransaction.sign(master);
                        Log.e("===", HexUtils.toHex(sign));
                    } catch (BitcoinException e) {
                        e.printStackTrace();
                    }

                    Log.e(LOGTAG, "privateKey = " + master.getPrivateKey());
                    Log.e(LOGTAG,  "publickey = " + master.getPublicKey());
                    Log.e(LOGTAG, "addresss = " + master.getAddress());
                    Log.e(LOGTAG, "raworuvatekey = " + DigitalTrans.byte2hex(master.getRawPrivateKey()));
                    Log.e(LOGTAG, "=========address end=============");

                } catch (MnemonicException.MnemonicLengthException e) {
                    e.printStackTrace();
                } catch (ValidationException e) {
                    e.printStackTrace();
                }

**Comment by QuincySx** [comment]
稍后我会看一下，估计是缓存我写的有漏洞

**Comment by zdyszm** [comment]
谢谢！

**Comment by QuincySx** [comment]
已修复
