### ISSUE TITLE
BTC测试私钥恢复会生成正式的地址

### ISSUE THREAD

**Issue by zdyszm** [QuincySx/BlockchainWallet-Crypto#12]
HI:
  用https://www.bitaddress.org/?testnet=true网站生产的私钥
使用BitCoinECKeyPair parseWIF恢复地址的时候 : 
(decode[0] == (byte) TEST_NET_PRIVATE_KEY_PREFIX  这个判断有问题。
我改为了这样才可以:
 int test = decode[0] & 0xFF;
        if ( test ==  TEST_NET_PRIVATE_KEY_PREFIX)

**Comment by QuincySx** [comment]
谢谢反馈
