### ISSUE TITLE
请教如何生成子地址？

### ISSUE THREAD

**Issue by SephirothLT** [QuincySx/BlockchainWallet-Crypto#22]
如何生成子地址，和获取到子地址的公私钥？

**Comment by SephirothLT** [comment]
针对BTC的，如何获取主地址？

**Comment by QuincySx** [comment]
请参考 [Wiki](https://github.com/QuincySx/BlockchainWallet-Crypto/wiki/5.-%E7%94%9F%E6%88%90%E5%AD%90%E7%A7%81%E9%92%A5-BIP-44-%E5%AD%90%E7%A7%81%E9%92%A5)

如果不想依照 Bip44 规范生成子私钥请参考 CoinPairDerive 类的源码
