### ISSUE TITLE
0.1.14-beta版本在jitpack上没有发布成功

### ISSUE THREAD

**Issue by jijunpeng** [QuincySx/BlockchainWallet-Crypto#23]
0.1.14-beta版本在jitpack上没有发布成功
https://jitpack.io/com/github/QuincySx/BlockchainWallet-Crypto/v0.1.14-beta/build.log

**Comment by QuincySx** [comment]
感谢提醒

**Comment by QuincySx** [comment]
jcenter 的问题有个一库下载超时了，已解决
