### ISSUE TITLE
transaction error

### ISSUE THREAD

**Issue by dalancon** [QuincySx/BlockchainWallet-Crypto#24]
i create a transaction,  i got a signed tx.  but  i an error when broadcast :

1、create a tx：
try {
                    BTCTransaction.Input[] inputs = new BTCTransaction.Input[1];
                    BTCTransaction.Output[] outputs = new BTCTransaction.Output[2];
                    BTCTransaction.OutPoint outPoint = new BTCTransaction.OutPoint(HexUtils.fromHex("0068a570118ff3cdde0a13f2a7aa3a4b3c2f8f094bc8980f7310daa1bcea3ed9"), 0);

                    inputs[0] = new BTCTransaction.Input(outPoint, null, 0xffffffff);

                    BTCTransaction.Output output1 = new BTCTransaction.Output(100, BTCTransaction.Script.buildOutput("mztEzH7tSzauW1vQmZ9NQog8VfJAsgtjLB"));
                    outputs[0] = output1;

                    BTCTransaction.Output output2 = new BTCTransaction.Output(1000, BTCTransaction.Script.buildOutput("mqQtNiy8YJgJUpT3DFtcXkKy1UVjLY4rPH"));
                    outputs[1] = output2;

                    BTCTransaction transaction = new BTCTransaction(inputs, outputs, 0);
//
                    byte[] sign = transaction.sign(master);
                    Log.e(TAG, HexUtils.toHex(sign));
                } catch (Exception e) {
                    e.printStackTrace();
                }

2、interface to return:
 Missing parents for 84ea32e77c6365b4463ab0de95223ff10cdcf34e53138598e487765aed657e81 while inserting: [0068a570118ff3cdde0a13f2a7aa3a4b3c2f8f094bc8980f7310daa1bcea3ed9]

help me!

**Comment by QuincySx** [comment]
What's the wrong message of your broadcast

**Comment by QuincySx** [comment]
Since you haven't replied for a long time, if you still have questions, please submit it to lssues again.

**Comment by dalancon** [comment]
new BTCTransaction.Input(outPoint, null, 0xffffffff);
the second param shoud inited what？
i pass null will report error

**Comment by QuincySx** [comment]
This is script, you click the source code to know
