### ISSUE TITLE
可以写一个获取btc transaction hash的例子吗

### ISSUE THREAD

**Issue by gexiao** [QuincySx/BlockchainWallet-Crypto#27]
可以写一个获取btc transaction hash的例子吗

**Comment by QuincySx** [comment]
使用比特币节点命令 (怎么搭节点自己去研究)
1. getblockcount  //获取当前区块高度
2. getblockhash 1382745 //获取区块 hash 参数是区块高度（只要不超过当前区块高度传入几都行）
3. getblock 区块Hash //获取区块信息
```
xxxxxxx
"tx": [
    "d6fe797adfbbf13bfa64e6763c2f81eae52972f4325f5a9d6715ab2a52a0f546",
    "e75b841c23cd4863e485a55863a8318a3f03f1e5a9f449fff0c6243c84ec28e7"
]
xxxx
```
4. 在 tx 数组中随便挑一个 tx
getrawtransaction tx //获取交易 hash
