### ISSUE TITLE
Library中的libscrypt.so是用来做什么的呢？

### ISSUE THREAD

**Issue by webgenie-team** [QuincySx/BlockchainWallet-Crypto#29]
我在源码中也没有搜索到 System.loadLibrary的调用。

**Comment by QuincySx** [comment]
so 文件是给 com.lambdaworks:scrypt:1.4.0 使用的，他内部只有 X86_64 的 so 文件
spongycastle 库的 Scrypt 算法会出现 OOM 的问题
详细参照 [web3j issues](https://github.com/web3j/web3j/issues/299)
