### ISSUE TITLE
助记词导入验证的时候，为什么12个相同的bip39单词也可以导入？

### ISSUE THREAD

**Issue by jasonz1987** [QuincySx/BlockchainWallet-Crypto#33]
比如 我输入12个相同的 bip39助记词，然后调用验证方法，竟然也可以验证通过，是什么情况呢？
```
  MnemonicValidator
                    .ofWordList(English.INSTANCE)
                    .validate(mnemonicStr);
```

**Comment by QuincySx** [comment]
因为 12 位助记词在验证的时候会出问题没找到原因，所以验证代码我暂时删掉了，等我找到原因我会重新加上的

**Comment by jasonz1987** [comment]
原作者NovaCrypto-BIP39的代码更新了，我用他的代码来验证了，目前没有问题，你看是不是要更新一下。

**Comment by QuincySx** [comment]
我稍后看看，怎么处理一下

**Comment by QuincySx** [comment]
我重新看了一下标准的 BIP39 描述，没有提到说单词不能重复，我也不知道这个验证该不该加

**Comment by bxxasn** [comment]
> 原作者NovaCrypto-BIP39的代码更新了，我用他的代码来验证了，目前没有问题，你看是不是要更新一下。

请问原作者的git地址是？

**Comment by QuincySx** [comment]
@bxxasn https://github.com/NovaCrypto/BIP39

**Comment by jasonz1987** [comment]
具体的描述不太清楚，但是按照常规思维来说如果重复单词能作为密钥，那么密钥也就不能称为密钥了吧。

**Comment by QuincySx** [comment]
按助记词的推理过程，是完全有可能重复的，只不过可能性极低
