### ISSUE TITLE
兼容bchABC/BSV

### ISSUE THREAD

**Issue by dalancon** [QuincySx/BlockchainWallet-Crypto#36]
你好：
       这个库可以兼容bchabc/bsv吗？
网上资料很少，可以给我一些建议吗？

**Comment by QuincySx** [comment]
我现在主要精力在 EOS 上 bchabc/bsv 我也没有什么好建议。
不过讲道理的说，我推测公私钥生成以及签名这些东西是不会变的。
可能是交易格式有略微的变化。
你可以去看一下关键源码。
https://github.com/Bitcoin-ABC/bitcoin-abc
https://github.com/bitcoin-sv/bitcoin-sv

**Comment by dalancon** [comment]
ok  谢谢

**Comment by dalancon** [comment]
请问区块链开发 有没有什么资料 可以推荐？ @QuincySx
