### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by jackTang11** [QuincySx/BlockchainWallet-Crypto#4]
很多平台都可以通过导入的方式来恢复,
那么也就说可以通过私钥去推算地址,我在你这里面试了很多方法不行,求助

助记词可以生成私钥和地址,已有
没有助记词,也可以用私钥推算出地址,暂无,求助

**Comment by QuincySx** [comment]
这个很简单根据私钥格式反推出 RawPrivateKey 就好了，只不过我还没写，这一块加到 TODO List 中，下个版本推出
