### ISSUE TITLE
java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by JinruiWang** [QuincySx/BlockchainWallet-Crypto#5]
我运行Sample的时候爆出这个异常，logcat定位在：
`java.lang.StackOverflowError: stack size 8MB
                      at com.quincysx.crypto.bitcoin.BTCTransaction.getSignBytes(BTCTransaction.java:111)
`
然后发现BTCTransaction这个方法是不是写错了？？
`    
@Override
public byte[] getSignBytes() {
    return getSignBytes();
}
`
自己调用自己，造成死循环？

**Comment by QuincySx** [comment]
感谢提醒，现已修复，如果使用的话可以用 Tag 里面最新的版本，master 分支代码还未测试
