### ISSUE TITLE
如何通过私钥来恢复祝记词和地址（BTC，ETH）

### ISSUE THREAD

**Issue by zdyszm** [QuincySx/BlockchainWallet-Crypto#6]
hi：
   能够通过祝记词来恢复地址了..
   但是如何通过私钥来恢复 BTC/ETCH的地址和私钥呢...

**Comment by QuincySx** [comment]
无法通过私钥恢复助记词

通过私钥生成地址下个版本更新

**Comment by zdyszm** [comment]
HI:
   非常感谢。刚试了..btc的确实可以通过这个方法来恢复.
   当时好像ETH的还不能恢复，请问ETH的什么时候可以通过私钥恢复地址呢?

**Comment by QuincySx** [comment]
byte[] keys = HexUtils.fromHex("去掉 0x 的 ETH 私钥");
ECKeyPair ecKeyPair = new ECKeyPair(keys, true);
EthECKeyPair.parse(ecKeyPair);

没写一次性生成的

**Comment by zdyszm** [comment]
谢谢答复..刚试了，确实可以
